---
#sandbox:
#client_id: '3MVG9rFJvQRVOvk4936qVmFb9yxKEdYXMT_XgaRSQwu0uIWXBa9JKV5pyYqQy1rR8E_gA8TJkir4t88wjQ0Ot'
#client_secret: '932864809905970491'

# production
client_id: '3MVG9rFJvQRVOvk4936qVmFb9y8OAdfxdd.1V3VjnXdFQqfsfOD_KDQyHRr.JT7vTZv9lGoDXGytkstPc1uFr'
client_secret: '8031231860605997305'



